### PR TITLE
MediaObject requires container to avoid transcode

### PR DESCRIPTION
**Pull request by bengeorge**
This plugin was transcoding.  It should direct play.

### CODE REVIEW

**Comment by bengeorge** [comment]
@sander1 How do we go about landing this ?

**Comment by sander1** [comment]
Hi! `AudioCodec.MP3` is not a valid value for container (see docs: https://us.v-cdn.net/6025034/uploads/editor/rg/jxvpxxxt63r6.pdf), but if this makes it work I'll check and see what `AudioCodec.MP3` is replaced with and maybe hardcoding that value makes it work.

**Comment by bengeorge** [comment]
Odd I thought I fixed that up: it should be `Container.MP3`.

**Comment by bengeorge** [comment]
Thanks for linking to the doc, I have not seen that :)

Although `Container.MP3` is not listed in the doc it seems it exists 😅 https://github.com/search?q=org%3Aplexinc-plugins+%22Container.Mp3%22&type=Code

**Comment by bengeorge** [comment]
Actually it doesn't seem to work, even though it is used in a bunch of places 😕   So maybe lets just hardcode as you suggested.

**Pull request merged**
